name: stllm-test1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - numpy=1.23.5 
  - pandas=1.5.3
  - matplotlib=3.6.3
  - protobuf=3.20.3
  - sentencepiece=0.1.99
  - transformers=4.26.1 
  - pip:
    - torchcde==0.2.5
    - nni==2.10
    - addict==2.4.0
    - modelscope>=1.9.3    
    - ms-swift==1.4.0
    - wandb


    # pip install torch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113